## MAINLY WHILE LOOP EXPLAIN ME & FOR LOOP ALSO WHAT DOES BACKEND HAPPEND???????

##### L O O P #################################
value=1
while value < 8:
    print(value),
    
###################   METHOD OVERLOADING  #####################################################
'''class Teacher:
    def new(self, name=None):
        if name is not None:
            print(name)
        elif name is None:
            print('i am the false')
        else:
            print('Welcome')
            
obj = Teacher()
obj.new()
obj.new('sam')


class Teacher:
    def new(self, name=None):
        if name is not None:
            print(name)
        elif name is not None:
            print('i am the false')
        else:
            print('Welcome')
            
obj = Teacher()
obj.new()
obj.new('sam')


class Teacher:
    def new(self, name=None):
        if name is None:
            print(name)
        elif name is None:
            print('i am the false')
        else:
            print('Welcome')
            
obj = Teacher()
obj.new()
obj.new('sam')'''


